name: CI/CD for cashier app
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: setup node js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: install dependencies
      run: npm install

    - name: cache node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashfiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Deploy to Railway
      uses: railwayapp/railway-github-action@v1
      with:
        railway_token: ${{ secrets.RAILWAY_API_TOKEN }}
        service_name: stellar-peace
